name: Daily Weather Collector

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-weather-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 👈 Required for branching

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run weather script
        env:
          GPT_API_KEY: ${{ secrets.GPT_API_KEY }}
          FREE_TIER_OPENWEATHERMAP_API_KEY: ${{ secrets.FREE_TIER_OPENWEATHERMAP_API_KEY }}
        run: python weather.py

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "🤖 Daily weather update [auto]"

      - name: Push to daily-data-updates branch (force update)
        run: |
          # Create the branch if it doesn't exist locally
          git checkout -B daily-data-updates
          
          # Push and overwrite remote branch
          git push --force origin HEAD:daily-data-updates

