name: Daily Weather Collector

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-weather-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 👈 Required for branching

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run weather script
        env:
          GPT_API_KEY: ${{ secrets.GPT_API_KEY }}
          FREE_TIER_OPENWEATHERMAP_API_KEY: ${{ secrets.FREE_TIER_OPENWEATHERMAP_API_KEY }}
        run: python weather.py

      - name: Commit weather data to 'daily-data-updates' branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Create new branch if it doesn't exist
          git fetch origin daily-data-updates || true
          git checkout -B daily-data-updates

          # Stage only the data file and logs
          git add data/cloud_cover.json
          git add logs/weather_log.txt

          git diff --cached --quiet || git commit -m "🤖 Daily weather update [auto]"

      - name: Force push to daily-data-updates branch
        run: |
          git push --force origin HEAD:daily-data-updates
