name: Daily Weather Collector

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-weather-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 👈 Required for branching

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Checkout daily-data-updates branch
        run: |
          git fetch origin
          if git show-ref --quiet refs/remotes/origin/daily-data-updates; then
            echo "✅ Branch 'daily-data-updates' exists. Checking out."
            git checkout daily-data-updates
            git pull origin daily-data-updates
          else
            echo "⚡ Branch 'daily-data-updates' does not exist. Creating it."
            git checkout -b daily-data-updates
          fi
      
      - name: Run weather script
        env:
          GPT_API_KEY: ${{ secrets.GPT_API_KEY }}
          FREE_TIER_OPENWEATHERMAP_API_KEY: ${{ secrets.FREE_TIER_OPENWEATHERMAP_API_KEY }}
        run: |
          python weather.py
      
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "🤖 Daily weather update [auto]" || echo "Nothing to commit"
          git push origin daily-data-updates